export const countries = [
  { dk: "Polen", en: "Poland", short: "POL" },
  { dk: "Afghanistan", en: "Afghanistan", short: "AFG" },
  { dk: "Iran", en: "Iran", short: "IRN" },
  { dk: "Grækenland", en: "Greece", short: "GRC" },
  { dk: "Nigeria", en: "Nigeria", short: "NGA" },
  { dk: "Syrien", en: "Syria", short: "SYR" },
  { dk: "Tyskland", en: "Germany", short: "DEU" },
  { dk: "Kroatien", en: "Croatia", short: "HRV" },
  { dk: "Sverige", en: "Sweden", short: "SWE" },
  { dk: "Belgien", en: "Belgium", short: "BEL" },
  { dk: "Italien", en: "Italy", short: "ITA" },
  {
    dk: "Den Demokratiske Republik Congo (DR Congo)",
    en: "Democratic Republic of the Congo",
    short: "COD",
  },
  { dk: "Statsløse palæstinensere", en: "Stateless Palestinians", short: "" }, // *********
  { dk: "Eritrea", en: "Eritrea", short: "ERI" },
  { dk: "Etiopien", en: "Ethiopia", short: "ETH" },
  { dk: "Spanien", en: "Spain", short: "ESP" },
  { dk: "Rumænien", en: "Romania", short: "ROU" },
  { dk: "Indien", en: "India", short: "IND" },
  { dk: "Libanon", en: "Lebanon", short: "LBN" },
  { dk: "Somalia", en: "Somalia", short: "SOM" },
  { dk: "Holland", en: "Netherlands", short: "NLD" },
  { dk: "Bulgarien", en: "Bulgaria", short: "BGR" },
  { dk: "Cameroun", en: "Cameroon", short: "CMR" },
  { dk: "Uganda", en: "Uganda", short: "UGA" },
  { dk: "Irak", en: "Iraq", short: "IRQ" },
  { dk: "Portugal", en: "Portugal", short: "PRT" },
  { dk: "Sri Lanka", en: "Sri Lanka", short: "LKA" },
  { dk: "Myanmar", en: "Myanmar", short: "MMR" },
  { dk: "Østrig", en: "Austria", short: "AUT" },
  { dk: "Frankrig", en: "France", short: "FRA" },
  { dk: "Tunesien", en: "Tunisia", short: "TUN" },
  { dk: "Bosnien-Hercegovina", en: "Bosnia and Herzegovina", short: "BIH" },
  { dk: "Malta", en: "Malta", short: "MLT" },
  { dk: "Belarus (Hviderusland)", en: "Belarus", short: "BLR" },
  { dk: "Vietnam", en: "Vietnam", short: "VNM" },
  { dk: "Burundi", en: "Burundi", short: "BDI" },
  { dk: "Marokko", en: "Morocco", short: "MAR" },
  { dk: "Armenien", en: "Armenia", short: "ARM" },
  { dk: "Georgien", en: "Georgia", short: "GEO" },
  { dk: "Egypten", en: "Egypt", short: "EGY" },
  { dk: "Libyen", en: "Libya", short: "LBY" },
  { dk: "Pakistan", en: "Pakistan", short: "PAK" },
  { dk: "Colombia", en: "Colombia", short: "COL" },
  { dk: "Algeriet", en: "Algeria", short: "DZA" },
  { dk: "Litauen", en: "Lithuania", short: "LTU" },
  { dk: "Kina", en: "China", short: "CHN" },
  { dk: "Bangladesh", en: "Bangladesh", short: "BGD" },
  {
    dk: "Anonymiseret hjemland",
    en: "Anonymized country of origin",
    short: "ANONYMOUS",
  },
  { dk: "Kosovo", en: "Kosovo", short: "XXK" },
  { dk: "Jordan", en: "Jordan", short: "JOR" },
  { dk: "Ukendt hjemland", en: "Unknown country of origin", short: "UNKNOWN" },
  { dk: "Schweiz", en: "Switzerland", short: "CHE" },
  { dk: "Tyrkiet", en: "Turkey", short: "TUR" },
  { dk: "Ghana", en: "Ghana", short: "GHA" },
  { dk: "Rusland", en: "Russia", short: "RUS" },
  { dk: "Norge", en: "Norway", short: "NOR" },
  { dk: "Slovenien", en: "Slovenia", short: "SVN" },
  { dk: "Finland", en: "Finland", short: "FIN" },
  { dk: "Rwanda", en: "Rwanda", short: "RWA" },
  { dk: "Island", en: "Iceland", short: "ISL" },
  { dk: "Letland", en: "Latvia", short: "LVA" },
  { dk: "Mauritanien", en: "Mauritania", short: "MRT" },
  { dk: "Sudan", en: "Sudan", short: "SDN" },
  { dk: "Nepal", en: "Nepal", short: "NPL" },
  { dk: "Kenya", en: "Kenya", short: "KEN" },
  { dk: "Guinea", en: "Guinea", short: "GIN" },
  { dk: "Uzbekistan", en: "Uzbekistan", short: "UZB" },
  { dk: "Zambia", en: "Zambia", short: "ZMB" },
  { dk: "Cypern", en: "Cyprus", short: "CYP" },
  { dk: "Ukraine", en: "Ukraine", short: "UKR" },
  { dk: "Albanien", en: "Albania", short: "ALB" },
  { dk: "Serbien", en: "Serbia", short: "SRB" },
  { dk: "Nordmakedonien", en: "North Macedonia", short: "MKD" },
  { dk: "Kasakhstan", en: "Kazakhstan", short: "KAZ" },
  { dk: "Angola", en: "Angola", short: "AGO" },
  { dk: "Israel", en: "Israel", short: "ISR" },
  { dk: "Kuwait", en: "Kuwait", short: "KWT" },
  { dk: "Yemen", en: "Yemen", short: "YEM" },
  { dk: "Venezuela", en: "Venezuela", short: "VEN" },
  { dk: "Brasilien", en: "Brazil", short: "BRA" },
  { dk: "Honduras", en: "Honduras", short: "HND" },
  { dk: "Nicaragua", en: "Nicaragua", short: "NIC" },
  { dk: "Indonesien", en: "Indonesia", short: "IDN" },
  { dk: "Malaysia", en: "Malaysia", short: "MYS" },
  { dk: "Zimbabwe", en: "Zimbabwe", short: "ZWE" },
  { dk: "Peru", en: "Peru", short: "PER" },
  { dk: "Namibia", en: "Namibia", short: "NAM" },
  { dk: "Sydsudan", en: "South Sudan", short: "SSD" },
  { dk: "Sierra Leone", en: "Sierra Leone", short: "SLE" },
  { dk: "Gambia", en: "Gambia", short: "GMB" },
  { dk: "El Salvador", en: "El Salvador", short: "SLV" },
  { dk: "Montenegro", en: "Montenegro", short: "MNE" },
  { dk: "Aserbajdsjan", en: "Azerbaijan", short: "AZE" },
  { dk: "Djibouti", en: "Djibouti", short: "DJI" },
  { dk: "Senegal", en: "Senegal", short: "SEN" },
  { dk: "Tanzania", en: "Tanzania", short: "TZA" },
  { dk: "Chile", en: "Chile", short: "CHL" },
  { dk: "Panama", en: "Panama", short: "PAN" },
  { dk: "Thailand", en: "Thailand", short: "THA" },
  { dk: "Ungarn", en: "Hungary", short: "HUN" },
  { dk: "Filippinerne", en: "Philippines", short: "PHL" },
  { dk: "Elfenbenskysten", en: "Ivory Coast", short: "CIV" },
  {
    dk: "Republikken Congo (Congo Brazzaville)",
    en: "Republic of Congo",
    short: "COG",
  },
  { dk: "Saudi-Arabien", en: "Saudi Arabia", short: "SAU" },
  { dk: "Gaza/Vestbredden", en: "Gaza/West Bank", short: "GAZ" },
  { dk: "Mali", en: "Mali", short: "MLI" },
  { dk: "Benin", en: "Benin", short: "BEN" },
  { dk: "Kirgisistan", en: "Kyrgyzstan", short: "KGZ" },
  { dk: "Guatemala", en: "Guatemala", short: "GTM" },
  { dk: "Sydkorea", en: "South Korea", short: "KOR" },
  { dk: "Cuba", en: "Cuba", short: "CUB" },
  { dk: "Diverse emner", en: "Miscellaneous topics", short: "MISC" },
  { dk: "Tchad", en: "Chad", short: "TCD" },
  { dk: "Sydafrika", en: "South Africa", short: "ZAF" },
  { dk: "Turkmenistan", en: "Turkmenistan", short: "TKM" },
  { dk: "Togo", en: "Togo", short: "TGO" },
  { dk: "Niger", en: "Niger", short: "NER" },
  { dk: "Moldova", en: "Moldova", short: "MDA" },
  { dk: "Liberia", en: "Liberia", short: "LBR" },
  { dk: "Haiti", en: "Haiti", short: "HTI" },
];
